version: '3.4'
services:
 php74-apache:
  #build: ./74-apache24/
  image: eurobertics/php-devenv:${PHPVERSION}-apache24
  ports:
    - 80:80
  volumes:
    - ${DOCKERWEBROOT}:/var/www/html
 redis:
  image: redis
  command:
   - --appendonly yes
  volumes:
   - ${DOCKERREDISROOT}:/data
 mariadb:
  image: mariadb
  environment:
   MYSQL_ROOT_PASSWORD: dockerphpdev
  volumes:
   - ${DOCKERSQLROOT}:/var/lib/mysql
