name: Build and Push Multiarch Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Notwendig für GHCR

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Images
        run: |
          PLATFORMS="linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7"
          IMAGE_NAME="eurobertics/php-devenv"
          EXCLUDE_DIRS=("74-apache24" "74-cli")

          for dir in */; do
            TAG="${dir%/}"
            DOCKERFILE="$dir/Dockerfile"

            # Prüfen, ob das Verzeichnis auf der Blacklist ist
            if [[ " ${EXCLUDE_DIRS[@]} " =~ " $TAG " ]]; then
              echo "Skipping $TAG (excluded from build)"
              continue
            fi

            if [ -f "$DOCKERFILE" ]; then
              echo "Building and pushing $IMAGE_NAME:$TAG"

              # GitHub Container Registry
              docker buildx build --platform $PLATFORMS \
                --push \
                -t ghcr.io/${{ secrets.GHCR_USERNAME }}/$IMAGE_NAME:$TAG \
                -f $DOCKERFILE $dir

              # Docker Hub
              docker buildx build --platform $PLATFORMS \
                --push \
                -t ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$TAG \
                -f $DOCKERFILE $dir
            else
              echo "No Dockerfile found in $dir, skipping..."
            fi
          done
